### ISSUE TITLE
Handle missing layers

### ISSUE THREAD

**Issue by basille** [mablab/rpostgisLT#11]
`pgtrajPlotter` should throw a warning (I think, not an error) in case of missing layers, e.g.:

```
pgtrajPlotter(conn, schema, pgtraj, layers = c("my_imaginary", "layer"))
```

**Comment by balazsdukai** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [issue#11 enhancement](https://trello.com/c/GycqqB5k/65-issue11-enhancement)
