### ISSUE TITLE
getLayers: sfc object should have crs set

### ISSUE THREAD

**Issue by basille** [mablab/rpostgisLT#12]
Using the colony shapefile inserted in the DB with `pgInsert`, and trying to have it as background layer:

```
pgtrajPlotter(conn, schema, pgtraj, layers = list(c("public", "colo")))
```

I get an error:

```
Error in st_transform.sfc(st_geometry(x), crs, ...) (from utils.R#211) : 
  sfc object should have crs set
In addition: Warning message:
In check_tzones(e1, e2) : 'tzone' attributes are inconsistent
```

Probably not a bug of `rpostgisLT` though. The error comes from the fact that `sf::st_read_db` does not recognize the CRS of the layer. Importing the layer with `rpostgis::pgGetGeom` gets the layer with the correct projection in R.

**Comment by balazsdukai** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [issue#12 bug](https://trello.com/c/5YI6F3YG/64-issue12-bug)

**Comment by balazsdukai** [comment]
The problem here is that `sf 0.5-3` doesn't handle custom CRS and the the file you mention is in a custom CRS. As a workaround I suggest that you transform the layer into a "standard" CRS, one that has an EPSG code assigned to it. Internally all layers are transformed to EPSG:4326 anyway.
