### ISSUE TITLE
Infinite time loop

### ISSUE THREAD

**Issue by basille** [mablab/rpostgisLT#2]
Simply loading the stork data (locally), and hitting `N` for a while, without changing any of the defaults, the time loops on a few increments (it goes forward for a few steps, then backwards from the beginning or almost), pretty much indefinitely. Not sure what's causing it, but that really prevents from moving forward in the trajectories.

**Comment by basille** [comment]
This does not happen if I hit the next key one at a time. But if I hit the key too fast, even just a couple of times, then it gets stuck in the loop for a very long time (can happen on two steps going back and forth for instance).

**Comment by balazsdukai** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [issue#2](https://trello.com/c/jQux9W90/56-issue2)

**Comment by balazsdukai** [comment]
fixed in 8f060e23b00b0ba829e956ec38e2e02afc0bdea8
