### ISSUE TITLE
Issue with burst selection

### ISSUE THREAD

**Issue by basille** [mablab/rpostgisLT#22]
With the data [bla.zip](https://github.com/mablab/rpostgisLT/files/1253175/bla.zip), extract it, and start with:

```r
library(rpostgisLT)
load("bla.RData")
ltraj2pgtraj(conn_local, ltraj = bla, schema = "test",
             pgtraj = "wost_ad", overwrite = TRUE)
explorePgtraj(conn_local, schema = "test",
              pgtraj = "wost_ad")
```

And try to reproduce the following situation (same parameters, time slider, etc.), with the zoom roughly over Florida:

![screenshot from 2017-08-26 00-42-15](https://user-images.githubusercontent.com/4000337/29735258-ebb77676-89f7-11e7-9c91-daaa6096f07e.png)

As you can see, individual 429190 is not selected, but is plotted anyway. I've been trying different ways, but I still get non-selected bursts plotted.

**Comment by balazsdukai** [comment]
This is the intended behaviour. Note two things:

1. The Bursts layer is off. Thus what you see are the steps that fall within the selected time window. 
2. Step mode is OFF. Thus you don't get detailed information on the selected steps but you get faster plotting.

If you would turn the Bursts layer on, you would see the bursts that you selected.

**Comment by basille** [comment]
Sorry I should have been more specific. I agree with your comments, but the problem is not here: If you look at the tooltip, this is animal/burst 429190, which is however not selected. I have played around a bit, but I couldn't have a complete match between the selection and the display of bursts — there was always bursts displayed that were not selected (but I couldn't see if there were also missing bursts). This is to me a major bug.

**Comment by balazsdukai** [comment]
>  If you look at the tooltip, this is animal/burst 429190, which is however not selected.

The burst 429190 is not selected in the *Bursts* selection box, but because you have the *Bursts* layer off (list of layers on the top left) you not looking at burst either, but *steps*. Thus what you see on the plot are the *steps* that are within the time range in the *Time window*. Among these steps, the purple ones belong to *animal/burst 429190*, thus when you click on them, you get this information. 

If you would turn the *Step mode* ON, you would see the detailed step parameters of these purple steps.

Does this answer your question?

(in the meantime check out the latest version where you can also turn the steps layer on/off)

**Comment by basille** [comment]
> Among these steps, the purple ones belong to animal/burst 429190, thus when you click on them, you get this information.

But why would they be displayed **in the first place**, since I did not selected this burst? I fail to understand the logic here: if I only select burst X, I want to explore the steps of burst X only.

OK for the _Step mode_, this works as I understand.

**Comment by balazsdukai** [comment]
>  if I only select burst X, I want to explore the steps of burst X only

I'm afraid that's not how it works. The *Bursts* selection box is independent from the *Time window*. This means that when you select a burst in the *Bursts* selection box, the whole burst is plotted, similarly to plotting the full trajectory. The difference is that when you click on a burst that you added through the *Bursts* box, you get all the parameters of that particular bursts. When you turn the *Bursts* layer off, all the bursts disappear that you selected in the *Bursts* box.

The *Time window* selects all steps within the time range, regardless which burst do they belong to. There is no possibility to filter these steps further. However, their color indicates which animal/burst they belong to. Also when you click on one, the popup shows you additional info.

Note that what you are looking for was not among requirements that we've discussed, hence it is not implemented.

**Comment by basille** [comment]
Ah, my bad then! :)

Now you probably understand some of our earlier discussions and my confusion about the app. 

So let me try to sum up here the behavior of the app:

- The app provides three layers: trajectories, bursts, steps. 
- The trajectory layer displays everything (all steps from all bursts) in the background, in thin lines of the same color (with no control on display parameters).
- The burst layer displays only selected bursts (all steps) with a different color by animal or burst (that can be set with the Color animal/burst switch). 
- The step layer displays all steps (from all bursts) within the temporal window defined by the time slider, and with a different color by animal or burst (that can be set with the Color animal/burst switch). Steps are drawn as a continuous line string by default, unless step mode is turned on (this also give access to detailed step information). 
- All three layers are displayed by default, but can be turned off individually. 

Is this correct?

Note that I didn't try the latest version yet, as I don't have access to my computer now... I'll do that as soon as possible.

**Comment by balazsdukai** [comment]
Yes, this is exactly how v0.6.0 works. Once you've tried the version and there is no related issue please close this Issue.

**Comment by basille** [comment]
OK, I have now installed and tried v0.6.0! Very impressive! It is very smooth, and works as described. I'm sorry though that I didn't managed to convey the idea that the selection was hierarchical: steps within bursts within trajectories. I am not sure I see a use case of having steps of non-selected bursts, but I' not blaming you for this! Sometimes, things can be so obvious to you that you fail to even realize it's not the case for everybody :)

I'm closing this issue as this is not a bug, but a feature intended by design. Now would my idea (all trajectories >> bursts >> steps) be at all feasible? Would this be a minor change (which means it only involves you or somebody else taking the time to adjust the code), or is it structurally more complicated, and would imply a major overhaul?

Note that this is the reason that I wanted an all/none selector for bursts, so that we can select steps and bursts quickly.

**Comment by balazsdukai** [comment]
It is feasible, rpostgisLT:::getStepWindow() needs an additional clause for the burst name in the SQL query, plus preparing the selected burst names for injecting into the query.

**Comment by basille** [comment]
So not unfeasible :)

Let's put it in the roadmap then!
