### ISSUE TITLE
Change of unit resets the value of the parameter

### ISSUE THREAD

**Issue by basille** [mablab/rpostgisLT#32]
Somewhat related to the link between the time slider and the Interval selector: As it is now, when one selects a different unit for any of Increment and Interval, the value gets reset to 0. It would be nice to have an automated translation on the fly.

`adehabitatLT` defines a [simple conversion utility function](https://github.com/ClementCalenge/adehabitatLT/blob/883832c12b742150de6441a247aad8a28a574f12/R/corrXY.r) as:

```
.convtime <- function(step, units)
{
        if (units=="min")
            step <- step*60
        if (units=="hour")
            step <- step*60*60
        if (units=="day")
            step <- step*60*60*24
        return(step)
}
```

This could be further developed to include months and years, but this can be tricky, as not every month (and not every year!) has the same number of days. Maybe using an approximation at the time of the current step could work.

**Comment by balazsdukai** [comment]
The increment/interval value resets to 0 on unit change only in case e.g. the increment==4, unit==hours –> unit==days. That is because 4 hours is 0 days.

**Comment by basille** [comment]
Ooooh… Is the increment constrained to be an integer then?

**Comment by balazsdukai** [comment]
Yes, because I thought a 0.x second interval/increment won't ever be necessary. For example if you need an interval of 0.x days then you should switch to hours.

**Comment by basille** [comment]
That makes sense! I guess I only played around with conversions to 0 (i.e. less than 24 hours converted to 0 day for instance), which is why I did not notice the conversion. Closing this one!
