### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by basille** [mablab/rpostgisLT#5]
* It would be good if the Increment/Interval and units box would have a minimal size, so that they don't get squished too much if you reduce the size of the window. See here, the Increment/Interval is not visible anymore (ideally, the Units could go below it when the width of the window is reduced):

![screenshot from 2017-07-14 13-31-47](https://user-images.githubusercontent.com/4000337/28223318-f4e7ec6a-6898-11e7-8930-8a6922d9294b.png)

* Can you try to maximize the size of the map, as to use as much space as available in the window?

* <del>Can you give a choice between OSM and a simple administrative map outline? (just to visualize land, countries and oceans)?</del> (I created a [dedicated issue for this one](https://github.com/mablab/rpostgisLT/issues/6))

**Comment by balazsdukai** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [issue#5](https://trello.com/c/RDTDp7eO/59-issue5)
