### ISSUE TITLE
Allow for any background layer(s)

### ISSUE THREAD

**Issue by basille** [mablab/rpostgisLT#6]
As the background, it would be nice if we could have any number of background layers that could be loaded instead of the OSM layer. It should stick to OSM by default, but allow (at the time of running the function) to provide a layer, or a list of layers stored in the DB.

For instance, in the case of the wood stork trajectories, I would load the outline of Florida (polygons) and the identified colonies (points).

Then, the same selector as currently available would be present on the canvas, as to activate or inactivate each loaded layers.

**Comment by basille** [comment]
Ideally, the first argument (`layers`?) would allow either a single element or a list of elements as input (elements being, I guess, in the form `c(schema, table)`), and a second argument (`display`?) would allow to define the drawing characteristics of each layer (need to give a bit more thoughts for the exact syntax).

**Comment by balazsdukai** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [add 'external' layers](https://trello.com/c/IHxOKaS8/52-add-external-layers)

**Comment by balazsdukai** [comment]
Implemented for vector layers in 940c06f232aec1e5978fd7b740d2a1c458a23b60 . Still need to resolve raster loading from database.

**Comment by balazsdukai** [comment]
Implemented for a single, local raster layers in 854b1ef1e23392341b27e39573e09f357b222bd6 . Raster layer need to be provided by the user and needs to be a `RasterLayer` object created with `raster::raster()`. Display parameters can be provided for `leaflet` the same way as for vector layers.
