### ISSUE TITLE
Use case: Find potential nesting sites

### ISSUE THREAD

**Issue by basille** [mablab/rpostgisLT#7]
Situation: in a huge dataset such as the wood stork one, we want to identify where wood stork have potentially nested. Nesting will look like very restricted movement starting in winter/spring, with regular "commutes" to foraging grounds (potentially the same for the entire season, but we don't know). So the need is to be able to quickly browse through the years for all trajectories, and be able to zoom in and move slower and back and forth when there is a potential site. Zooming will allow to identify if this corresponds to a potential nesting site (e.g. wetland with OSM) or a known colony (point data).

**Comment by basille** [comment]
A similar use case, with pretty much the same "signature" would be to identify predation events on the predator trajectories. They will look like clusters of points in a short period of time, with the predator potentially coming back to it for several days.

**Comment by balazsdukai** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Use case #](https://trello.com/c/2cyN2hqu/60-use-case)

**Comment by balazsdukai** [comment]
I believe this is addressed by the current time slider. You can drag the slider to quickly browse through a trajectory, eventually adjust the interval/increment. Then you can zoom in the map and also in time by setting a smaller increment and interval. Finally use the Next/Back buttons to proceed step-by-step. Does this answer your case?

**Comment by basille** [comment]
Yes, I think it does. I will have to try it with the latest `dev` though.

Just thinking out loud here: How hard would it be to have a `Play` and `Pause` button? In effect, `Play` would be just like pressing `Next` permanently, but would allow to interact dynamically with the display of the map (spanning, zooming). `Pause` would simply stop the progress. Ideally, there would be just one button, in between `Back` and `Next`, that would turn into `Play` or `Pause` accordingly.

Definitely not a must-have, but if that looks super easy to do, that would be kind of cool to have!
