### ISSUE TITLE
Use case: Highlight interactions

### ISSUE THREAD

**Issue by basille** [mablab/rpostgisLT#8]
Situation: With several individuals monitored, I want to highlight potential interactions, that is individuals very close to each other in space and time. Using again the wood stork data, we would browse quickly through all individuals simultaneously to see if they get close to each other. Zooming and browsing slower would allow to "refine" the conclusions, and look at environmental features (including again known colonies).

**Comment by basille** [comment]
Here too, the same perspective can be taken from a predator-prey perspective, by browsing simultaneously predators and prey (trickier here, because they are most likely from different `ltraj`s/`pgtraj`s) and see if the predators ever come close to the prey. In this case, an interesting feature would be to look at habitat characteristics in the area (often times in a raster).

**Comment by balazsdukai** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Use case:](https://trello.com/c/CJCdaDkI/61-use-case)

**Comment by balazsdukai** [comment]
How would you define *"very close to each other in space and time"*? Are there values that you can use to evaluate this, or do you mainly do it by the eye?

**Comment by basille** [comment]
Yes, it would be really by the eye, and it would entirely depend on the species/context. Then, if you can see that, indeed, individuals get close to each other, you would run an analysis to quantify it (in PostgreSQL or R).

Thinking about it, would it be possible to have a scale bar in one of the corner of the map?
