### ISSUE TITLE
Use case: Identifying occurrence and timing of migration

### ISSUE THREAD

**Issue by basille** [mablab/rpostgisLT#9]
Situation: similar than the nesting site situation, except that we now operate at a much larger scale — migration happens at the scale of Florida in the case of wood storks. So browsing here would be again with all individuals simultaneously, but probably at a larger time scale. We would want to identify the initiation and end days for the migration.

**Comment by balazsdukai** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Use case:](https://trello.com/c/youscdmy/62-use-case)

**Comment by balazsdukai** [comment]
Does the time slider answer your case (as described in #7 )?

**Comment by basille** [comment]
Yes, I think it does. See my request of [automatic play](https://github.com/mablab/rpostgisLT/issues/7#issuecomment-324654646).
